using MadMilkman.Ini;
using System;
using System.IO;
using System.Windows.Forms;

namespace NEWRTL
{
    internal class INIHandler
    {
        public static void Save(string Section, string Key, string Value)
        {
            try
            {

                IniFile file = new IniFile();
                file.Load(Constants.INIPath);
                if (!file.Sections.Contains(Section))
                {
                    file.Sections.Add(Section);
                }
                if (!file.Sections[Section].Keys.Contains(Key))
                {
                    file.Sections[Section].Keys.Add(Key);
                    file.Sections[Section].Keys[Key].Value = Value;
                }
                else
                {
                    file.Sections[Section].Keys[Key].Value = Value;
                }

                // Logger.WriteLog("Saving Value: " + Key + " + " + Value);

                file.Save(Constants.INIPath);
            }
            catch (Exception ex)
            {
                if (MessageBox.Show(ex.ToString() + "\n\nPlease send this error message to a developer, alongside ReTHAWedLaunch-Log.txt", "CATASTROPHIC SAVING ERROR", MessageBoxButtons.OK, MessageBoxIcon.Error) == DialogResult.OK)
                {
                    if (MessageBox.Show("Would you like to do a full refresh of your settings?\n This could potentially resolve this error.", "reTHAWed Support", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        System.Media.SystemSounds.Asterisk.Play();
                        generateINI();
                    }
                }

            }
        }

        public static void generateINI()
        {
            //Generate a default INI file for the user, We be generous out here.
            using (StreamWriter sw = new StreamWriter(Constants.INIPath, true))
            {
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine(";");
                sw.WriteLine(";          reTHAWed");
                sw.WriteLine(";        Configuration");
                sw.WriteLine("; GENERATED BY RETHAWED LAUNCHER");
                sw.WriteLine(";");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Debug]");
                sw.WriteLine("Autolaunch=mainmenu");
                sw.WriteLine("DefaultButtonFont=0");
                sw.WriteLine("ShowMemory=0");
                sw.WriteLine("UnlockFPSValue=0");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Logger]");
                sw.WriteLine("Console=0");
                sw.WriteLine("WriteFile=1");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Misc]");
                sw.WriteLine("RichPresence=1");
                sw.WriteLine("EnteredFirstStartup=0");
                sw.WriteLine("IntroMovies=0");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Graphics]");
                sw.WriteLine("ResolutionX=1280");
                sw.WriteLine("ResolutionY=720");
                sw.WriteLine("Windowed=1");
                sw.WriteLine("Borderless=0");
                sw.WriteLine("SafeArea=Wide");
                sw.WriteLine("Bloom=1");
                sw.WriteLine("Shadows=2");
                sw.WriteLine("DistanceClipping=0");
                sw.WriteLine("FullRange=0");
                sw.WriteLine("ClippingDistance=100");
                sw.WriteLine("Fog=0");
                sw.WriteLine("AspectRatio=16:9");
                sw.WriteLine("ButtonFont=ButtonsPC");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Keybinds]");
                sw.WriteLine("Forward=26");
                sw.WriteLine("Backward=22");
                sw.WriteLine("Left=4");
                sw.WriteLine("Right=7");
                sw.WriteLine("Ollie=90");
                sw.WriteLine("Grab=94");
                sw.WriteLine("Flip=92");
                sw.WriteLine("Grind=96");
                sw.WriteLine("SpinLeft=89");
                sw.WriteLine("SpinRight=91");
                sw.WriteLine("Nollie=95");
                sw.WriteLine("Caveman=8");
                sw.WriteLine("CameraUp=12");
                sw.WriteLine("CameraDown=14");
                sw.WriteLine("CameraLeft=13");
                sw.WriteLine("CameraRight=15");
                sw.WriteLine("ViewToggle=9");
                sw.WriteLine("SwivelLock=53");
                sw.WriteLine("Focus=88");
                sw.WriteLine("SpineTransfer=44");
                sw.WriteLine("ItemUp=82");
                sw.WriteLine("ItemDown=81");
                sw.WriteLine("ItemLeft=80");
                sw.WriteLine("ItemRight=79");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Gamepad]");
                sw.WriteLine("Pause=6");
                sw.WriteLine("ViewToggle=4");
                sw.WriteLine("SwivelLock=8");
                sw.WriteLine("Grind=3");
                sw.WriteLine("Grab=1");
                sw.WriteLine("Ollie=0");
                sw.WriteLine("Flip=2");
                sw.WriteLine("SpinLeft=9");
                sw.WriteLine("SpinRight=10");
                sw.WriteLine("Nollie=22");
                sw.WriteLine("Switch=21");
                sw.WriteLine("Right=14");
                sw.WriteLine("Left=13");
                sw.WriteLine("Forward=11");
                sw.WriteLine("Backward=12");
                sw.WriteLine("MovementStick=0");
                sw.WriteLine("CameraStick=1");
                sw.WriteLine("Focus=7");
                sw.WriteLine("; Only when Ps2Controls are disabled!");
                sw.WriteLine("Caveman=10");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Config]");
                sw.WriteLine("AllowHolidays=1");
                sw.WriteLine("");
                sw.WriteLine("; ---------------------------------");
                sw.WriteLine("");
                sw.WriteLine("[Theme]");
                sw.WriteLine("BalanceBar=THAW");
                sw.WriteLine("SpecialMeter=THAW");
            }
            //Wait just to make sure the process above finishes properly, then restart our app.
            //GlobalFunc.FadeOut(Constants.mainWindow, 15);
            GlobalFunc.wait(1000);
            Application.Restart();
            Environment.Exit(0);

        }
    }
}
