using System.Windows.Forms;

namespace NEWRTL
{
    internal class SDLHandler
    {
        const int SDL_SCANCODE_UNKNOWN = 0;
        const int SDL_SCANCODE_A = 4;
        const int SDL_SCANCODE_B = 5;
        const int SDL_SCANCODE_C = 6;
        const int SDL_SCANCODE_D = 7;
        const int SDL_SCANCODE_E = 8;
        const int SDL_SCANCODE_F = 9;
        const int SDL_SCANCODE_G = 10;
        const int SDL_SCANCODE_H = 11;
        const int SDL_SCANCODE_I = 12;
        const int SDL_SCANCODE_J = 13;
        const int SDL_SCANCODE_K = 14;
        const int SDL_SCANCODE_L = 15;
        const int SDL_SCANCODE_M = 16;
        const int SDL_SCANCODE_N = 17;
        const int SDL_SCANCODE_O = 18;
        const int SDL_SCANCODE_P = 19;
        const int SDL_SCANCODE_Q = 20;
        const int SDL_SCANCODE_R = 21;
        const int SDL_SCANCODE_S = 22;
        const int SDL_SCANCODE_T = 23;
        const int SDL_SCANCODE_U = 24;
        const int SDL_SCANCODE_V = 25;
        const int SDL_SCANCODE_W = 26;
        const int SDL_SCANCODE_X = 27;
        const int SDL_SCANCODE_Y = 28;
        const int SDL_SCANCODE_Z = 29;
        const int SDL_SCANCODE_1 = 30;
        const int SDL_SCANCODE_2 = 31;
        const int SDL_SCANCODE_3 = 32;
        const int SDL_SCANCODE_4 = 33;
        const int SDL_SCANCODE_5 = 34;
        const int SDL_SCANCODE_6 = 35;
        const int SDL_SCANCODE_7 = 36;
        const int SDL_SCANCODE_8 = 37;
        const int SDL_SCANCODE_9 = 38;
        const int SDL_SCANCODE_0 = 39;
        const int SDL_SCANCODE_RETURN = 40;
        const int SDL_SCANCODE_ESCAPE = 41;
        const int SDL_SCANCODE_BACKSPACE = 42;
        const int SDL_SCANCODE_TAB = 43;
        const int SDL_SCANCODE_SPACE = 44;
        const int SDL_SCANCODE_MINUS = 45;
        const int SDL_SCANCODE_EQUALS = 46;
        const int SDL_SCANCODE_LEFTBRACKET = 47;
        const int SDL_SCANCODE_RIGHTBRACKET = 48;
        const int SDL_SCANCODE_BACKSLASH = 49;
        const int SDL_SCANCODE_NONUSHASH = 50;
        const int SDL_SCANCODE_SEMICOLON = 51;
        const int SDL_SCANCODE_APOSTROPHE = 52;
        const int SDL_SCANCODE_GRAVE = 53;
        const int SDL_SCANCODE_COMMA = 54;
        const int SDL_SCANCODE_PERIOD = 55;
        const int SDL_SCANCODE_SLASH = 56;
        const int SDL_SCANCODE_CAPSLOCK = 57;
        const int SDL_SCANCODE_F1 = 58;
        const int SDL_SCANCODE_F2 = 59;
        const int SDL_SCANCODE_F3 = 60;
        const int SDL_SCANCODE_F4 = 61;
        const int SDL_SCANCODE_F5 = 62;
        const int SDL_SCANCODE_F6 = 63;
        const int SDL_SCANCODE_F7 = 64;
        const int SDL_SCANCODE_F8 = 65;
        const int SDL_SCANCODE_F9 = 66;
        const int SDL_SCANCODE_F10 = 67;
        const int SDL_SCANCODE_F11 = 68;
        const int SDL_SCANCODE_F12 = 69;
        const int SDL_SCANCODE_PRINTSCREEN = 70;
        const int SDL_SCANCODE_SCROLLLOCK = 71;
        const int SDL_SCANCODE_PAUSE = 72;
        const int SDL_SCANCODE_INSERT = 73;
        const int SDL_SCANCODE_HOME = 74;
        const int SDL_SCANCODE_PAGEUP = 75;
        const int SDL_SCANCODE_DELETE = 76;
        const int SDL_SCANCODE_END = 77;
        const int SDL_SCANCODE_PAGEDOWN = 78;
        const int SDL_SCANCODE_RIGHT = 79;
        const int SDL_SCANCODE_LEFT = 80;
        const int SDL_SCANCODE_DOWN = 81;
        const int SDL_SCANCODE_UP = 82;
        const int SDL_SCANCODE_NUMLOCKCLEAR = 83;
        const int SDL_SCANCODE_KP_DIVIDE = 84;
        const int SDL_SCANCODE_KP_MULTIPLY = 85;
        const int SDL_SCANCODE_KP_MINUS = 86;
        const int SDL_SCANCODE_KP_PLUS = 87;
        const int SDL_SCANCODE_KP_ENTER = 88;
        const int SDL_SCANCODE_KP_1 = 89;
        const int SDL_SCANCODE_KP_2 = 90;
        const int SDL_SCANCODE_KP_3 = 91;
        const int SDL_SCANCODE_KP_4 = 92;
        const int SDL_SCANCODE_KP_5 = 93;
        const int SDL_SCANCODE_KP_6 = 94;
        const int SDL_SCANCODE_KP_7 = 95;
        const int SDL_SCANCODE_KP_8 = 96;
        const int SDL_SCANCODE_KP_9 = 97;
        const int SDL_SCANCODE_KP_0 = 98;
        const int SDL_SCANCODE_KP_PERIOD = 99;
        const int SDL_SCANCODE_NONUSBACKSLASH = 100;
        const int SDL_SCANCODE_APPLICATION = 101;
        const int SDL_SCANCODE_POWER = 102;
        const int SDL_SCANCODE_KP_EQUALS = 103;
        const int SDL_SCANCODE_F13 = 104;
        const int SDL_SCANCODE_F14 = 105;
        const int SDL_SCANCODE_F15 = 106;
        const int SDL_SCANCODE_F16 = 107;
        const int SDL_SCANCODE_F17 = 108;
        const int SDL_SCANCODE_F18 = 109;
        const int SDL_SCANCODE_F19 = 110;
        const int SDL_SCANCODE_F20 = 111;
        const int SDL_SCANCODE_F21 = 112;
        const int SDL_SCANCODE_F22 = 113;
        const int SDL_SCANCODE_F23 = 114;
        const int SDL_SCANCODE_F24 = 115;
        const int SDL_SCANCODE_EXECUTE = 116;
        const int SDL_SCANCODE_HELP = 117;
        const int SDL_SCANCODE_MENU = 118;
        const int SDL_SCANCODE_SELECT = 119;
        const int SDL_SCANCODE_STOP = 120;
        const int SDL_SCANCODE_AGAIN = 121;
        const int SDL_SCANCODE_UNDO = 122;
        const int SDL_SCANCODE_CUT = 123;
        const int SDL_SCANCODE_COPY = 124;
        const int SDL_SCANCODE_PASTE = 125;
        const int SDL_SCANCODE_FIND = 126;
        const int SDL_SCANCODE_MUTE = 127;
        const int SDL_SCANCODE_VOLUMEUP = 128;
        const int SDL_SCANCODE_VOLUMEDOWN = 129;
        const int SDL_SCANCODE_LOCKINGCAPSLOCK = 130;
        const int SDL_SCANCODE_LOCKINGNUMLOCK = 131;
        const int SDL_SCANCODE_LOCKINGSCROLLLOCK = 132;
        const int SDL_SCANCODE_KP_COMMA = 133;
        const int SDL_SCANCODE_KP_EQUALSAS400 = 134;
        const int SDL_SCANCODE_INTERNATIONAL1 = 135;
        const int SDL_SCANCODE_INTERNATIONAL2 = 136;
        const int SDL_SCANCODE_INTERNATIONAL3 = 137;
        const int SDL_SCANCODE_INTERNATIONAL4 = 138;
        const int SDL_SCANCODE_INTERNATIONAL5 = 139;
        const int SDL_SCANCODE_INTERNATIONAL6 = 140;
        const int SDL_SCANCODE_INTERNATIONAL7 = 141;
        const int SDL_SCANCODE_INTERNATIONAL8 = 142;
        const int SDL_SCANCODE_INTERNATIONAL9 = 143;
        const int SDL_SCANCODE_LANG1 = 144;
        const int SDL_SCANCODE_LANG2 = 145;
        const int SDL_SCANCODE_LANG3 = 146;
        const int SDL_SCANCODE_LANG4 = 147;
        const int SDL_SCANCODE_LANG5 = 148;
        const int SDL_SCANCODE_LANG6 = 149;
        const int SDL_SCANCODE_LANG7 = 150;
        const int SDL_SCANCODE_LANG8 = 151;
        const int SDL_SCANCODE_LANG9 = 152;
        const int SDL_SCANCODE_ALTERASE = 153;
        const int SDL_SCANCODE_SYSREQ = 154;
        const int SDL_SCANCODE_CANCEL = 155;
        const int SDL_SCANCODE_CLEAR = 156;
        const int SDL_SCANCODE_PRIOR = 157;
        const int SDL_SCANCODE_RETURN2 = 158;
        const int SDL_SCANCODE_SEPARATOR = 159;
        const int SDL_SCANCODE_OUT = 160;
        const int SDL_SCANCODE_OPER = 161;
        const int SDL_SCANCODE_CLEARAGAIN = 162;
        const int SDL_SCANCODE_CRSEL = 163;
        const int SDL_SCANCODE_EXSEL = 164;
        const int SDL_SCANCODE_KP_00 = 176;
        const int SDL_SCANCODE_KP_000 = 177;
        const int SDL_SCANCODE_THOUSANDSSEPARATOR = 178;
        const int SDL_SCANCODE_DECIMALSEPARATOR = 179;
        const int SDL_SCANCODE_CURRENCYUNIT = 180;
        const int SDL_SCANCODE_CURRENCYSUBUNIT = 181;
        const int SDL_SCANCODE_KP_LEFTPAREN = 182;
        const int SDL_SCANCODE_KP_RIGHTPAREN = 183;
        const int SDL_SCANCODE_KP_LEFTBRACE = 184;
        const int SDL_SCANCODE_KP_RIGHTBRACE = 185;
        const int SDL_SCANCODE_KP_TAB = 186;
        const int SDL_SCANCODE_KP_BACKSPACE = 187;
        const int SDL_SCANCODE_KP_A = 188;
        const int SDL_SCANCODE_KP_B = 189;
        const int SDL_SCANCODE_KP_C = 190;
        const int SDL_SCANCODE_KP_D = 191;
        const int SDL_SCANCODE_KP_E = 192;
        const int SDL_SCANCODE_KP_F = 193;
        const int SDL_SCANCODE_KP_XOR = 194;
        const int SDL_SCANCODE_KP_POWER = 195;
        const int SDL_SCANCODE_KP_PERCENT = 196;
        const int SDL_SCANCODE_KP_LESS = 197;
        const int SDL_SCANCODE_KP_GREATER = 198;
        const int SDL_SCANCODE_KP_AMPERSAND = 199;
        const int SDL_SCANCODE_KP_DBLAMPERSAND = 200;
        const int SDL_SCANCODE_KP_VERTICALBAR = 201;
        const int SDL_SCANCODE_KP_DBLVERTICALBAR = 202;
        const int SDL_SCANCODE_KP_COLON = 203;
        const int SDL_SCANCODE_KP_HASH = 204;
        const int SDL_SCANCODE_KP_SPACE = 205;
        const int SDL_SCANCODE_KP_AT = 206;
        const int SDL_SCANCODE_KP_EXCLAM = 207;
        const int SDL_SCANCODE_KP_MEMSTORE = 208;
        const int SDL_SCANCODE_KP_MEMRECALL = 209;
        const int SDL_SCANCODE_KP_MEMCLEAR = 210;
        const int SDL_SCANCODE_KP_MEMADD = 211;
        const int SDL_SCANCODE_KP_MEMSUBTRACT = 212;
        const int SDL_SCANCODE_KP_MEMMULTIPLY = 213;
        const int SDL_SCANCODE_KP_MEMDIVIDE = 214;
        const int SDL_SCANCODE_KP_PLUSMINUS = 215;
        const int SDL_SCANCODE_KP_CLEAR = 216;
        const int SDL_SCANCODE_KP_CLEARENTRY = 217;
        const int SDL_SCANCODE_KP_BINARY = 218;
        const int SDL_SCANCODE_KP_OCTAL = 219;
        const int SDL_SCANCODE_KP_DECIMAL = 220;
        const int SDL_SCANCODE_KP_HEXADECIMAL = 221;
        const int SDL_SCANCODE_LCTRL = 224;
        const int SDL_SCANCODE_LSHIFT = 225;
        const int SDL_SCANCODE_LALT = 226;
        const int SDL_SCANCODE_LGUI = 227;
        const int SDL_SCANCODE_RCTRL = 228;
        const int SDL_SCANCODE_RSHIFT = 229;
        const int SDL_SCANCODE_RALT = 230;
        const int SDL_SCANCODE_RGUI = 231;
        const int SDL_SCANCODE_MODE = 257;
        const int SDL_SCANCODE_AUDIONEXT = 258;
        const int SDL_SCANCODE_AUDIOPREV = 259;
        const int SDL_SCANCODE_AUDIOSTOP = 260;
        const int SDL_SCANCODE_AUDIOPLAY = 261;
        const int SDL_SCANCODE_AUDIOMUTE = 262;
        const int SDL_SCANCODE_MEDIASELECT = 263;
        const int SDL_SCANCODE_WWW = 264;
        const int SDL_SCANCODE_MAIL = 265;
        const int SDL_SCANCODE_CALCULATOR = 266;
        const int SDL_SCANCODE_COMPUTER = 267;
        const int SDL_SCANCODE_AC_SEARCH = 268;
        const int SDL_SCANCODE_AC_HOME = 269;
        const int SDL_SCANCODE_AC_BACK = 270;
        const int SDL_SCANCODE_AC_FORWARD = 271;
        const int SDL_SCANCODE_AC_STOP = 272;
        const int SDL_SCANCODE_AC_REFRESH = 273;
        const int SDL_SCANCODE_AC_BOOKMARKS = 274;
        const int SDL_SCANCODE_BRIGHTNESSDOWN = 275;
        const int SDL_SCANCODE_BRIGHTNESSUP = 276;
        const int SDL_SCANCODE_DISPLAYSWITCH = 277;
        const int SDL_SCANCODE_KBDILLUMTOGGLE = 278;
        const int SDL_SCANCODE_KBDILLUMDOWN = 279;
        const int SDL_SCANCODE_KBDILLUMUP = 280;
        const int SDL_SCANCODE_EJECT = 281;
        const int SDL_SCANCODE_SLEEP = 282;

        public static int ConvertToSDL(Keys key)
        {
            switch (key)
            {
                case Keys.A: return SDL_SCANCODE_A;
                case Keys.B: return SDL_SCANCODE_B;
                case Keys.C: return SDL_SCANCODE_C;
                case Keys.D: return SDL_SCANCODE_D;
                case Keys.E: return SDL_SCANCODE_E;
                case Keys.F: return SDL_SCANCODE_F;
                case Keys.G: return SDL_SCANCODE_G;
                case Keys.H: return SDL_SCANCODE_H;
                case Keys.I: return SDL_SCANCODE_I;
                case Keys.J: return SDL_SCANCODE_J;
                case Keys.K: return SDL_SCANCODE_K;
                case Keys.L: return SDL_SCANCODE_L;
                case Keys.M: return SDL_SCANCODE_M;
                case Keys.N: return SDL_SCANCODE_N;
                case Keys.O: return SDL_SCANCODE_O;
                case Keys.P: return SDL_SCANCODE_P;
                case Keys.Q: return SDL_SCANCODE_Q;
                case Keys.R: return SDL_SCANCODE_R;
                case Keys.S: return SDL_SCANCODE_S;
                case Keys.T: return SDL_SCANCODE_T;
                case Keys.U: return SDL_SCANCODE_U;
                case Keys.V: return SDL_SCANCODE_V;
                case Keys.W: return SDL_SCANCODE_W;
                case Keys.X: return SDL_SCANCODE_X;
                case Keys.Y: return SDL_SCANCODE_Y;
                case Keys.Z: return SDL_SCANCODE_Z;

                case Keys.D1: return SDL_SCANCODE_1;
                case Keys.D2: return SDL_SCANCODE_2;
                case Keys.D3: return SDL_SCANCODE_3;
                case Keys.D4: return SDL_SCANCODE_4;
                case Keys.D5: return SDL_SCANCODE_5;
                case Keys.D6: return SDL_SCANCODE_6;
                case Keys.D7: return SDL_SCANCODE_7;
                case Keys.D8: return SDL_SCANCODE_8;
                case Keys.D9: return SDL_SCANCODE_9;
                case Keys.D0: return SDL_SCANCODE_0;

                case Keys.Return: return SDL_SCANCODE_RETURN;
                case Keys.Escape: return SDL_SCANCODE_ESCAPE;
                case Keys.Back: return SDL_SCANCODE_BACKSPACE;
                case Keys.Tab: return SDL_SCANCODE_TAB;
                case Keys.Space: return SDL_SCANCODE_SPACE;

                case Keys.OemMinus: return SDL_SCANCODE_MINUS;
                case Keys.Oemplus: return SDL_SCANCODE_EQUALS;
                case Keys.OemQuestion: return SDL_SCANCODE_NONUSHASH;
                case Keys.Oem1: return SDL_SCANCODE_SEMICOLON;
                case Keys.Oemtilde: return SDL_SCANCODE_UNKNOWN;
                case Keys.Oem7: return SDL_SCANCODE_UNKNOWN;
                case Keys.Oem5: return SDL_SCANCODE_GRAVE;
                case Keys.OemPeriod: return SDL_SCANCODE_PERIOD;
                case Keys.Oemcomma: return SDL_SCANCODE_COMMA;
                case Keys.OemOpenBrackets: return SDL_SCANCODE_LEFTBRACKET;
                case Keys.OemCloseBrackets: return SDL_SCANCODE_RIGHTBRACKET;
                case Keys.OemBackslash: return SDL_SCANCODE_BACKSLASH;

                case Keys.F1: return SDL_SCANCODE_F1;
                case Keys.F2: return SDL_SCANCODE_F2;
                case Keys.F3: return SDL_SCANCODE_F3;
                case Keys.F4: return SDL_SCANCODE_F4;
                case Keys.F5: return SDL_SCANCODE_F5;
                case Keys.F6: return SDL_SCANCODE_F6;
                case Keys.F7: return SDL_SCANCODE_F7;
                case Keys.F8: return SDL_SCANCODE_F8;
                case Keys.F9: return SDL_SCANCODE_F9;
                case Keys.F10: return SDL_SCANCODE_F10;
                case Keys.F11: return SDL_SCANCODE_F11;
                case Keys.F12: return SDL_SCANCODE_F12;

                case Keys.Print: return SDL_SCANCODE_PRINTSCREEN;
                case Keys.Scroll: return SDL_SCANCODE_SCROLLLOCK;
                case Keys.Pause: return SDL_SCANCODE_PAUSE;
                case Keys.Insert: return SDL_SCANCODE_INSERT;
                case Keys.Home: return SDL_SCANCODE_HOME;
                case Keys.PageUp: return SDL_SCANCODE_PAGEUP;
                case Keys.Delete: return SDL_SCANCODE_DELETE;
                case Keys.End: return SDL_SCANCODE_END;
                case Keys.PageDown: return SDL_SCANCODE_PAGEDOWN;
                case Keys.Right: return SDL_SCANCODE_RIGHT;
                case Keys.Left: return SDL_SCANCODE_LEFT;
                case Keys.Down: return SDL_SCANCODE_DOWN;
                case Keys.Up: return SDL_SCANCODE_UP;

                case Keys.Divide: return SDL_SCANCODE_KP_DIVIDE;
                case Keys.Multiply: return SDL_SCANCODE_KP_MULTIPLY;
                case Keys.Subtract: return SDL_SCANCODE_KP_MINUS;
                case Keys.Add: return SDL_SCANCODE_KP_PLUS;

                case Keys.NumPad1: return SDL_SCANCODE_KP_1;
                case Keys.NumPad2: return SDL_SCANCODE_KP_2;
                case Keys.NumPad3: return SDL_SCANCODE_KP_3;
                case Keys.NumPad4: return SDL_SCANCODE_KP_4;
                case Keys.NumPad5: return SDL_SCANCODE_KP_5;
                case Keys.NumPad6: return SDL_SCANCODE_KP_6;
                case Keys.NumPad7: return SDL_SCANCODE_KP_7;
                case Keys.NumPad8: return SDL_SCANCODE_KP_8;
                case Keys.NumPad9: return SDL_SCANCODE_KP_9;
                case Keys.NumPad0: return SDL_SCANCODE_KP_0;
                case Keys.LControlKey: return SDL_SCANCODE_LCTRL;
                case Keys.RControlKey: return SDL_SCANCODE_RCTRL;
                case Keys.RShiftKey: return SDL_SCANCODE_RSHIFT;
                case Keys.LShiftKey: return SDL_SCANCODE_LSHIFT;

                default: return SDL_SCANCODE_UNKNOWN;
            }
        }
        public static string ConvertFromSDL(int SDL_Scancode)
        {
            switch (SDL_Scancode)
            {
                case 0: return "";
                case 4: return "A";
                case 5: return "B";
                case 6: return "C";
                case 7: return "D";
                case 8: return "E";
                case 9: return "F";
                case 10: return "G";
                case 11: return "H";
                case 12: return "I";
                case 13: return "J";
                case 14: return "K";
                case 15: return "L";
                case 16: return "M";
                case 17: return "N";
                case 18: return "O";
                case 19: return "P";
                case 20: return "Q";
                case 21: return "R";
                case 22: return "S";
                case 23: return "T";
                case 24: return "U";
                case 25: return "V";
                case 26: return "W";
                case 27: return "X";
                case 28: return "Y";
                case 29: return "Z";
                case 30: return "1";
                case 31: return "2";
                case 32: return "3";
                case 33: return "4";
                case 34: return "5";
                case 35: return "6";
                case 36: return "7";
                case 37: return "8";
                case 38: return "9";
                case 39: return "0";
                case 40: return "Return";
                case 41: return "Escape";
                case 42: return "Backspace";
                case 43: return "TAB";
                case 44: return "Spacebar";
                case 45: return "Minus";
                case 46: return "Equals";
                case 47: return "Left Bracket";
                case 48: return "Right Bracket";
                case 49: return "Back Slash";
                case 50: return "Non-US Back Slash";
                case 51: return "Semi Colon";
                case 53: return "Grave";
                case 54: return "Comma";
                case 55: return "Period";
                case 58: return "F1";
                case 59: return "F2";
                case 60: return "F3";
                case 61: return "F4";
                case 62: return "F5";
                case 63: return "F6";
                case 64: return "F7";
                case 65: return "F8";
                case 66: return "F9";
                case 67: return "F10";
                case 68: return "F11";
                case 69: return "F12";
                case 70: return "PrintScreen";
                case 71: return "ScrollLock";
                case 72: return "Pause";
                case 73: return "Insert";
                case 74: return "Home";
                case 75: return "PageUp";
                case 76: return "Delete";
                case 77: return "End";
                case 78: return "PageDown";
                case 79: return "Right";
                case 80: return "Left";
                case 81: return "Down";
                case 82: return "Up";
                case 84: return "Divide";
                case 85: return "Multiply";
                case 86: return "Minus";
                case 87: return "Plus";
                case 89: return "KP 1";
                case 90: return "KP 2";
                case 91: return "KP 3";
                case 92: return "KP 4";
                case 93: return "KP 5";
                case 94: return "KP 6";
                case 95: return "KP 7";
                case 96: return "KP 8";
                case 97: return "KP 9";
                case 98: return "KP 0";
                case 88: return "Enter";
                case 228: return "RControlKey";
                case 229: return "RShiftKey";
                case 224: return "LControlKey";
                case 225: return "LShiftKey";


                default: return "";
            }
        }
    }
}